function createfigure(X1, Y1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 12-Jun-2013 01:47:23

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1);

% Create xlabel
xlabel('t (ns)','FontSize',14);

% Create ylabel
ylabel('T (K)','FontSize',14);

